# Configuration file for OriginalSkyblockDrops plugin
# You can set your own drop percentages and drop amounts here or even disable drops completely
# If you set a number that's more/less than the set maximum/minimum, plugin will automatically use default value

# Gravel drops from Zombies
# Gravel drop percentage (Default = 20, Min: 1, Max: 100)
# Gravel drop amount (Default = 1, Min: 1, Max: 10)
# Gravel drop disable/enable (false = drop enabled , true = drop disabled)
gravel_perc : 20
gravel_amount: 1
gravel_disable: false

# Sand drops from Husks
# Sand drop percentage (Default = 20, Min: 1, Max: 100)
# Sand drop amount (Default = 1, Min: 1, Max: 10)
# Sand drop disable/enable (false = drop enabled , true = drop disabled)
sand_perc : 20
sand_amount : 1
sand_disable: false

# Quartz drops from Blazes
# Quartz drop percentage (Default = 20, Min: 1, Max: 100)
# Quartz drop amount (Default = 1, Min: 1, Max: 10)
# Quartz drop disable/enable (false = drop enabled , true = drop disabled)
quartz_perc : 20
quartz_amount : 1
quartz_disable: false

# Soul Sand drops from Wither Skeletons
# Soul Sand drop percentage (Default = 20, Min: 1, Max: 100)
# Soul Sand drop amount (Default = 1, Min: 1, Max: 10)
# Soul Sand drop disable/enable (false = drop enabled , true = drop disabled)
soul_sand_perc : 20
soul_sand_amount : 1
soul_sand_disable: false

# Magma Cream drops from Zombified Piglins
# Magma Cream drop percentage (Default = 15, Min: 1, Max: 100)
# Magma Cream drop amount (Default = 1, Min: 1, Max: 10)
# Magma Cream drop disable/enable (false = drop enabled , true = drop disabled)
magma_cream_perc : 15
magma_cream_amount : 1
magma_cream_disable: false

# End of config file