name: Skyblockdrops
version: 2.1
main: me.minecraft.plugin.skyblockdrops.Skyblockdrops
api-version: 1.21
authors: [ JustErikSK ]
description: This plugin brings new loot for some mobs. Plugin is highly configurable using config.yml! Now with a Halloween event!