name: Skyblockdrops
version: 1.2.1_1.20.4
main: me.minecraft.plugin.skyblockdrops.Skyblockdrops
api-version: 1.20
authors: [ JustErikSK ]
description: This plugin brings new loot for zombies, blazes, husks and wither skeletons. We also added new drops for withers and zombified piglins.
