name: Skyblockdrops
version: 2
main: me.minecraft.plugin.skyblockdrops.versions.Skyblockdrops_1_21_1
api-version: 1.21
authors: [ JustErikSK ]
description: This plugin brings new loot for zombies, husks, skeletons, blazes, wither skeletons, withers and zombified piglins. Plugin is highly configurable using config.yml! Now with a Halloween event!